// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: internal/qc/preset.proto

package qc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryPreset struct {
	state                    protoimpl.MessageState      `protogen:"open.v1"`
	Name                     string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hash                     uint32                      `protobuf:"varint,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Date                     string                      `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Volume                   float32                     `protobuf:"fixed32,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Pan                      float32                     `protobuf:"fixed32,6,opt,name=pan,proto3" json:"pan,omitempty"`
	DefaultScene             uint32                      `protobuf:"varint,7,opt,name=default_scene,json=defaultScene,proto3" json:"default_scene,omitempty"`
	AuthorName               string                      `protobuf:"bytes,8,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorId                 string                      `protobuf:"bytes,9,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Tempo                    uint32                      `protobuf:"varint,10,opt,name=tempo,proto3" json:"tempo,omitempty"`
	Chains                   []*Chain                    `protobuf:"bytes,11,rep,name=chains,proto3" json:"chains,omitempty"`
	Tags                     []string                    `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	LegacyStompModeStompData []*LegacyStompModeStompData `protobuf:"bytes,13,rep,name=legacy_stomp_mode_stomp_data,json=legacyStompModeStompData,proto3" json:"legacy_stomp_mode_stomp_data,omitempty"`
	SceneTempo               []uint32                    `protobuf:"varint,14,rep,packed,name=scene_tempo,json=sceneTempo,proto3" json:"scene_tempo,omitempty"`
	SceneLabels              []string                    `protobuf:"bytes,15,rep,name=scene_labels,json=sceneLabels,proto3" json:"scene_labels,omitempty"`
	MidiMessages             []*MidiMessageInfo          `protobuf:"bytes,16,rep,name=midi_messages,json=midiMessages,proto3" json:"midi_messages,omitempty"`
	MidiMessagesGeneral      []*MidiMessageInfo          `protobuf:"bytes,17,rep,name=midi_messages_general,json=midiMessagesGeneral,proto3" json:"midi_messages_general,omitempty"`
	Bypass                   []*Bypass                   `protobuf:"bytes,18,rep,name=bypass,proto3" json:"bypass,omitempty"`
	TempoProgramData         []*Model                    `protobuf:"bytes,19,rep,name=tempoProgramData,proto3" json:"tempoProgramData,omitempty"`
	LayoutCode_1             []uint32                    `protobuf:"varint,20,rep,packed,name=layout_code_1,json=layoutCode1,proto3" json:"layout_code_1,omitempty"`
	LayoutCode_2             []uint32                    `protobuf:"varint,21,rep,packed,name=layout_code_2,json=layoutCode2,proto3" json:"layout_code_2,omitempty"`
	CreatedVersion           []string                    `protobuf:"bytes,22,rep,name=created_version,json=createdVersion,proto3" json:"created_version,omitempty"`
	ModifiedVersion          []string                    `protobuf:"bytes,23,rep,name=modified_version,json=modifiedVersion,proto3" json:"modified_version,omitempty"`
	OldestCompatibleVersion  []string                    `protobuf:"bytes,24,rep,name=oldest_compatible_version,json=oldestCompatibleVersion,proto3" json:"oldest_compatible_version,omitempty"`
	CloudId                  []string                    `protobuf:"bytes,25,rep,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	Description              []string                    `protobuf:"bytes,26,rep,name=description,proto3" json:"description,omitempty"`
	StompModeAssignments     []*StompModeAssignment      `protobuf:"bytes,27,rep,name=stomp_mode_assignments,json=stompModeAssignments,proto3" json:"stomp_mode_assignments,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BinaryPreset) Reset() {
	*x = BinaryPreset{}
	mi := &file_internal_qc_preset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryPreset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryPreset) ProtoMessage() {}

func (x *BinaryPreset) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryPreset.ProtoReflect.Descriptor instead.
func (*BinaryPreset) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{0}
}

func (x *BinaryPreset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BinaryPreset) GetHash() uint32 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *BinaryPreset) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *BinaryPreset) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *BinaryPreset) GetPan() float32 {
	if x != nil {
		return x.Pan
	}
	return 0
}

func (x *BinaryPreset) GetDefaultScene() uint32 {
	if x != nil {
		return x.DefaultScene
	}
	return 0
}

func (x *BinaryPreset) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *BinaryPreset) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *BinaryPreset) GetTempo() uint32 {
	if x != nil {
		return x.Tempo
	}
	return 0
}

func (x *BinaryPreset) GetChains() []*Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *BinaryPreset) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BinaryPreset) GetLegacyStompModeStompData() []*LegacyStompModeStompData {
	if x != nil {
		return x.LegacyStompModeStompData
	}
	return nil
}

func (x *BinaryPreset) GetSceneTempo() []uint32 {
	if x != nil {
		return x.SceneTempo
	}
	return nil
}

func (x *BinaryPreset) GetSceneLabels() []string {
	if x != nil {
		return x.SceneLabels
	}
	return nil
}

func (x *BinaryPreset) GetMidiMessages() []*MidiMessageInfo {
	if x != nil {
		return x.MidiMessages
	}
	return nil
}

func (x *BinaryPreset) GetMidiMessagesGeneral() []*MidiMessageInfo {
	if x != nil {
		return x.MidiMessagesGeneral
	}
	return nil
}

func (x *BinaryPreset) GetBypass() []*Bypass {
	if x != nil {
		return x.Bypass
	}
	return nil
}

func (x *BinaryPreset) GetTempoProgramData() []*Model {
	if x != nil {
		return x.TempoProgramData
	}
	return nil
}

func (x *BinaryPreset) GetLayoutCode_1() []uint32 {
	if x != nil {
		return x.LayoutCode_1
	}
	return nil
}

func (x *BinaryPreset) GetLayoutCode_2() []uint32 {
	if x != nil {
		return x.LayoutCode_2
	}
	return nil
}

func (x *BinaryPreset) GetCreatedVersion() []string {
	if x != nil {
		return x.CreatedVersion
	}
	return nil
}

func (x *BinaryPreset) GetModifiedVersion() []string {
	if x != nil {
		return x.ModifiedVersion
	}
	return nil
}

func (x *BinaryPreset) GetOldestCompatibleVersion() []string {
	if x != nil {
		return x.OldestCompatibleVersion
	}
	return nil
}

func (x *BinaryPreset) GetCloudId() []string {
	if x != nil {
		return x.CloudId
	}
	return nil
}

func (x *BinaryPreset) GetDescription() []string {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *BinaryPreset) GetStompModeAssignments() []*StompModeAssignment {
	if x != nil {
		return x.StompModeAssignments
	}
	return nil
}

type Chain struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Models             []*Model               `protobuf:"bytes,5,rep,name=models,proto3" json:"models,omitempty"`
	SplitControlPoints []*SplitControlPoints  `protobuf:"bytes,6,rep,name=split_control_points,json=splitControlPoints,proto3" json:"split_control_points,omitempty"`
	Splitter           []*Model               `protobuf:"bytes,7,rep,name=splitter,proto3" json:"splitter,omitempty"`
	Mixer              []*Model               `protobuf:"bytes,8,rep,name=mixer,proto3" json:"mixer,omitempty"`
	OutputControl      []*Model               `protobuf:"bytes,9,rep,name=output_control,json=outputControl,proto3" json:"output_control,omitempty"`
	SplitBypass        []*SceneBypass         `protobuf:"bytes,10,rep,name=splitBypass,proto3" json:"splitBypass,omitempty"`
	MixBypass          []*SceneBypass         `protobuf:"bytes,11,rep,name=mixBypass,proto3" json:"mixBypass,omitempty"`
	CombinedSplitter   []*Model               `protobuf:"bytes,12,rep,name=combined_splitter,json=combinedSplitter,proto3" json:"combined_splitter,omitempty"`
	InputControl       []*Model               `protobuf:"bytes,13,rep,name=input_control,json=inputControl,proto3" json:"input_control,omitempty"`
	// Types that are valid to be assigned to XInPortid:
	//
	//	*Chain_InPortid
	XInPortid isChain_XInPortid `protobuf_oneof:"_in_portid"`
	// Types that are valid to be assigned to XOutPortid:
	//
	//	*Chain_OutPortid
	XOutPortid isChain_XOutPortid `protobuf_oneof:"_out_portid"`
	// Types that are valid to be assigned to XRow:
	//
	//	*Chain_Row
	XRow          isChain_XRow `protobuf_oneof:"_row"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chain) Reset() {
	*x = Chain{}
	mi := &file_internal_qc_preset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{1}
}

func (x *Chain) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Chain) GetSplitControlPoints() []*SplitControlPoints {
	if x != nil {
		return x.SplitControlPoints
	}
	return nil
}

func (x *Chain) GetSplitter() []*Model {
	if x != nil {
		return x.Splitter
	}
	return nil
}

func (x *Chain) GetMixer() []*Model {
	if x != nil {
		return x.Mixer
	}
	return nil
}

func (x *Chain) GetOutputControl() []*Model {
	if x != nil {
		return x.OutputControl
	}
	return nil
}

func (x *Chain) GetSplitBypass() []*SceneBypass {
	if x != nil {
		return x.SplitBypass
	}
	return nil
}

func (x *Chain) GetMixBypass() []*SceneBypass {
	if x != nil {
		return x.MixBypass
	}
	return nil
}

func (x *Chain) GetCombinedSplitter() []*Model {
	if x != nil {
		return x.CombinedSplitter
	}
	return nil
}

func (x *Chain) GetInputControl() []*Model {
	if x != nil {
		return x.InputControl
	}
	return nil
}

func (x *Chain) GetXInPortid() isChain_XInPortid {
	if x != nil {
		return x.XInPortid
	}
	return nil
}

func (x *Chain) GetInPortid() uint32 {
	if x != nil {
		if x, ok := x.XInPortid.(*Chain_InPortid); ok {
			return x.InPortid
		}
	}
	return 0
}

func (x *Chain) GetXOutPortid() isChain_XOutPortid {
	if x != nil {
		return x.XOutPortid
	}
	return nil
}

func (x *Chain) GetOutPortid() uint32 {
	if x != nil {
		if x, ok := x.XOutPortid.(*Chain_OutPortid); ok {
			return x.OutPortid
		}
	}
	return 0
}

func (x *Chain) GetXRow() isChain_XRow {
	if x != nil {
		return x.XRow
	}
	return nil
}

func (x *Chain) GetRow() uint32 {
	if x != nil {
		if x, ok := x.XRow.(*Chain_Row); ok {
			return x.Row
		}
	}
	return 0
}

type isChain_XInPortid interface {
	isChain_XInPortid()
}

type Chain_InPortid struct {
	InPortid uint32 `protobuf:"varint,1,opt,name=in_portid,json=inPortid,proto3,oneof"`
}

func (*Chain_InPortid) isChain_XInPortid() {}

type isChain_XOutPortid interface {
	isChain_XOutPortid()
}

type Chain_OutPortid struct {
	OutPortid uint32 `protobuf:"varint,2,opt,name=out_portid,json=outPortid,proto3,oneof"`
}

func (*Chain_OutPortid) isChain_XOutPortid() {}

type isChain_XRow interface {
	isChain_XRow()
}

type Chain_Row struct {
	Row uint32 `protobuf:"varint,14,opt,name=row,proto3,oneof"`
}

func (*Chain_Row) isChain_XRow() {}

type Model struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	Params               []*Param                `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	BypassExpression     []*Expression           `protobuf:"bytes,3,rep,name=bypass_expression,json=bypassExpression,proto3" json:"bypass_expression,omitempty"`
	ExpressionBypassInfo []*ExpressionBypassInfo `protobuf:"bytes,4,rep,name=expression_bypass_info,json=expressionBypassInfo,proto3" json:"expression_bypass_info,omitempty"`
	// Types that are valid to be assigned to XHash:
	//
	//	*Model_Hash
	XHash isModel_XHash `protobuf_oneof:"_hash"`
	// Types that are valid to be assigned to XColumn:
	//
	//	*Model_Column
	XColumn       isModel_XColumn `protobuf_oneof:"_column"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_internal_qc_preset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{2}
}

func (x *Model) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Model) GetBypassExpression() []*Expression {
	if x != nil {
		return x.BypassExpression
	}
	return nil
}

func (x *Model) GetExpressionBypassInfo() []*ExpressionBypassInfo {
	if x != nil {
		return x.ExpressionBypassInfo
	}
	return nil
}

func (x *Model) GetXHash() isModel_XHash {
	if x != nil {
		return x.XHash
	}
	return nil
}

func (x *Model) GetHash() uint32 {
	if x != nil {
		if x, ok := x.XHash.(*Model_Hash); ok {
			return x.Hash
		}
	}
	return 0
}

func (x *Model) GetXColumn() isModel_XColumn {
	if x != nil {
		return x.XColumn
	}
	return nil
}

func (x *Model) GetColumn() uint32 {
	if x != nil {
		if x, ok := x.XColumn.(*Model_Column); ok {
			return x.Column
		}
	}
	return 0
}

type isModel_XHash interface {
	isModel_XHash()
}

type Model_Hash struct {
	Hash uint32 `protobuf:"varint,1,opt,name=hash,proto3,oneof"`
}

func (*Model_Hash) isModel_XHash() {}

type isModel_XColumn interface {
	isModel_XColumn()
}

type Model_Column struct {
	Column uint32 `protobuf:"varint,5,opt,name=column,proto3,oneof"`
}

func (*Model_Column) isModel_XColumn() {}

type SplitControlPoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Split         int32                  `protobuf:"varint,1,opt,name=split,proto3" json:"split,omitempty"`
	Mix           int32                  `protobuf:"varint,2,opt,name=mix,proto3" json:"mix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitControlPoints) Reset() {
	*x = SplitControlPoints{}
	mi := &file_internal_qc_preset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitControlPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitControlPoints) ProtoMessage() {}

func (x *SplitControlPoints) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitControlPoints.ProtoReflect.Descriptor instead.
func (*SplitControlPoints) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{3}
}

func (x *SplitControlPoints) GetSplit() int32 {
	if x != nil {
		return x.Split
	}
	return 0
}

func (x *SplitControlPoints) GetMix() int32 {
	if x != nil {
		return x.Mix
	}
	return 0
}

type Bypass struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ColBypass []*ColBypass           `protobuf:"bytes,1,rep,name=colBypass,proto3" json:"colBypass,omitempty"`
	// Types that are valid to be assigned to XRow:
	//
	//	*Bypass_Row
	XRow          isBypass_XRow `protobuf_oneof:"_row"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bypass) Reset() {
	*x = Bypass{}
	mi := &file_internal_qc_preset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bypass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bypass) ProtoMessage() {}

func (x *Bypass) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bypass.ProtoReflect.Descriptor instead.
func (*Bypass) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{4}
}

func (x *Bypass) GetColBypass() []*ColBypass {
	if x != nil {
		return x.ColBypass
	}
	return nil
}

func (x *Bypass) GetXRow() isBypass_XRow {
	if x != nil {
		return x.XRow
	}
	return nil
}

func (x *Bypass) GetRow() uint32 {
	if x != nil {
		if x, ok := x.XRow.(*Bypass_Row); ok {
			return x.Row
		}
	}
	return 0
}

type isBypass_XRow interface {
	isBypass_XRow()
}

type Bypass_Row struct {
	Row uint32 `protobuf:"varint,2,opt,name=row,proto3,oneof"`
}

func (*Bypass_Row) isBypass_XRow() {}

type ColBypass struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SceneBypass []*SceneBypass         `protobuf:"bytes,1,rep,name=sceneBypass,proto3" json:"sceneBypass,omitempty"`
	// Types that are valid to be assigned to XColumn:
	//
	//	*ColBypass_Column
	XColumn       isColBypass_XColumn `protobuf_oneof:"_column"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColBypass) Reset() {
	*x = ColBypass{}
	mi := &file_internal_qc_preset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColBypass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColBypass) ProtoMessage() {}

func (x *ColBypass) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColBypass.ProtoReflect.Descriptor instead.
func (*ColBypass) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{5}
}

func (x *ColBypass) GetSceneBypass() []*SceneBypass {
	if x != nil {
		return x.SceneBypass
	}
	return nil
}

func (x *ColBypass) GetXColumn() isColBypass_XColumn {
	if x != nil {
		return x.XColumn
	}
	return nil
}

func (x *ColBypass) GetColumn() uint32 {
	if x != nil {
		if x, ok := x.XColumn.(*ColBypass_Column); ok {
			return x.Column
		}
	}
	return 0
}

type isColBypass_XColumn interface {
	isColBypass_XColumn()
}

type ColBypass_Column struct {
	Column uint32 `protobuf:"varint,2,opt,name=column,proto3,oneof"`
}

func (*ColBypass_Column) isColBypass_XColumn() {}

type SceneBypass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bypass        bool                   `protobuf:"varint,1,opt,name=bypass,proto3" json:"bypass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneBypass) Reset() {
	*x = SceneBypass{}
	mi := &file_internal_qc_preset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneBypass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneBypass) ProtoMessage() {}

func (x *SceneBypass) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneBypass.ProtoReflect.Descriptor instead.
func (*SceneBypass) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{6}
}

func (x *SceneBypass) GetBypass() bool {
	if x != nil {
		return x.Bypass
	}
	return false
}

type Param struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ParamValues []*ParamValue          `protobuf:"bytes,5,rep,name=param_values,json=paramValues,proto3" json:"param_values,omitempty"`
	// Types that are valid to be assigned to XExpression:
	//
	//	*Param_Expression
	XExpression isParam_XExpression `protobuf_oneof:"_expression"`
	// Types that are valid to be assigned to XExpressionMin:
	//
	//	*Param_ExpressionMin
	XExpressionMin isParam_XExpressionMin `protobuf_oneof:"_expression_min"`
	// Types that are valid to be assigned to XExpressionMax:
	//
	//	*Param_ExpressionMax
	XExpressionMax isParam_XExpressionMax `protobuf_oneof:"_expression_max"`
	// Types that are valid to be assigned to XSceneMode:
	//
	//	*Param_SceneMode
	XSceneMode isParam_XSceneMode `protobuf_oneof:"_scene_mode"`
	// Types that are valid to be assigned to XIndex:
	//
	//	*Param_Index
	XIndex        isParam_XIndex `protobuf_oneof:"_index"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_internal_qc_preset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{7}
}

func (x *Param) GetParamValues() []*ParamValue {
	if x != nil {
		return x.ParamValues
	}
	return nil
}

func (x *Param) GetXExpression() isParam_XExpression {
	if x != nil {
		return x.XExpression
	}
	return nil
}

func (x *Param) GetExpression() int32 {
	if x != nil {
		if x, ok := x.XExpression.(*Param_Expression); ok {
			return x.Expression
		}
	}
	return 0
}

func (x *Param) GetXExpressionMin() isParam_XExpressionMin {
	if x != nil {
		return x.XExpressionMin
	}
	return nil
}

func (x *Param) GetExpressionMin() float32 {
	if x != nil {
		if x, ok := x.XExpressionMin.(*Param_ExpressionMin); ok {
			return x.ExpressionMin
		}
	}
	return 0
}

func (x *Param) GetXExpressionMax() isParam_XExpressionMax {
	if x != nil {
		return x.XExpressionMax
	}
	return nil
}

func (x *Param) GetExpressionMax() float32 {
	if x != nil {
		if x, ok := x.XExpressionMax.(*Param_ExpressionMax); ok {
			return x.ExpressionMax
		}
	}
	return 0
}

func (x *Param) GetXSceneMode() isParam_XSceneMode {
	if x != nil {
		return x.XSceneMode
	}
	return nil
}

func (x *Param) GetSceneMode() bool {
	if x != nil {
		if x, ok := x.XSceneMode.(*Param_SceneMode); ok {
			return x.SceneMode
		}
	}
	return false
}

func (x *Param) GetXIndex() isParam_XIndex {
	if x != nil {
		return x.XIndex
	}
	return nil
}

func (x *Param) GetIndex() uint32 {
	if x != nil {
		if x, ok := x.XIndex.(*Param_Index); ok {
			return x.Index
		}
	}
	return 0
}

type isParam_XExpression interface {
	isParam_XExpression()
}

type Param_Expression struct {
	Expression int32 `protobuf:"varint,1,opt,name=expression,proto3,oneof"`
}

func (*Param_Expression) isParam_XExpression() {}

type isParam_XExpressionMin interface {
	isParam_XExpressionMin()
}

type Param_ExpressionMin struct {
	ExpressionMin float32 `protobuf:"fixed32,2,opt,name=expression_min,json=expressionMin,proto3,oneof"`
}

func (*Param_ExpressionMin) isParam_XExpressionMin() {}

type isParam_XExpressionMax interface {
	isParam_XExpressionMax()
}

type Param_ExpressionMax struct {
	ExpressionMax float32 `protobuf:"fixed32,3,opt,name=expression_max,json=expressionMax,proto3,oneof"`
}

func (*Param_ExpressionMax) isParam_XExpressionMax() {}

type isParam_XSceneMode interface {
	isParam_XSceneMode()
}

type Param_SceneMode struct {
	SceneMode bool `protobuf:"varint,4,opt,name=scene_mode,json=sceneMode,proto3,oneof"`
}

func (*Param_SceneMode) isParam_XSceneMode() {}

type isParam_XIndex interface {
	isParam_XIndex()
}

type Param_Index struct {
	Index uint32 `protobuf:"varint,6,opt,name=index,proto3,oneof"`
}

func (*Param_Index) isParam_XIndex() {}

type ParamValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ParamValue_IntValue
	//	*ParamValue_FloatValue
	//	*ParamValue_StringValue
	Value         isParamValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamValue) Reset() {
	*x = ParamValue{}
	mi := &file_internal_qc_preset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamValue) ProtoMessage() {}

func (x *ParamValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamValue.ProtoReflect.Descriptor instead.
func (*ParamValue) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{8}
}

func (x *ParamValue) GetValue() isParamValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ParamValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*ParamValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *ParamValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*ParamValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *ParamValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ParamValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

type isParamValue_Value interface {
	isParamValue_Value()
}

type ParamValue_IntValue struct {
	IntValue int32 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type ParamValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,2,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type ParamValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*ParamValue_IntValue) isParamValue_Value() {}

func (*ParamValue_FloatValue) isParamValue_Value() {}

func (*ParamValue_StringValue) isParamValue_Value() {}

type LegacyStompModeStompData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           uint32                 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column        uint32                 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LegacyStompModeStompData) Reset() {
	*x = LegacyStompModeStompData{}
	mi := &file_internal_qc_preset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegacyStompModeStompData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegacyStompModeStompData) ProtoMessage() {}

func (x *LegacyStompModeStompData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegacyStompModeStompData.ProtoReflect.Descriptor instead.
func (*LegacyStompModeStompData) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{9}
}

func (x *LegacyStompModeStompData) GetRow() uint32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *LegacyStompModeStompData) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type StompModeAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           uint32                 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column        uint32                 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	StompIndex    uint32                 `protobuf:"varint,3,opt,name=stomp_index,json=stompIndex,proto3" json:"stomp_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StompModeAssignment) Reset() {
	*x = StompModeAssignment{}
	mi := &file_internal_qc_preset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StompModeAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StompModeAssignment) ProtoMessage() {}

func (x *StompModeAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StompModeAssignment.ProtoReflect.Descriptor instead.
func (*StompModeAssignment) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{10}
}

func (x *StompModeAssignment) GetRow() uint32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *StompModeAssignment) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *StompModeAssignment) GetStompIndex() uint32 {
	if x != nil {
		return x.StompIndex
	}
	return 0
}

type MidiMessageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Channel       uint32                 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Param1        uint32                 `protobuf:"varint,3,opt,name=param1,proto3" json:"param1,omitempty"`
	Param2        uint32                 `protobuf:"varint,4,opt,name=param2,proto3" json:"param2,omitempty"`
	Param3        uint32                 `protobuf:"varint,5,opt,name=param3,proto3" json:"param3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MidiMessageInfo) Reset() {
	*x = MidiMessageInfo{}
	mi := &file_internal_qc_preset_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MidiMessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MidiMessageInfo) ProtoMessage() {}

func (x *MidiMessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MidiMessageInfo.ProtoReflect.Descriptor instead.
func (*MidiMessageInfo) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{11}
}

func (x *MidiMessageInfo) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MidiMessageInfo) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *MidiMessageInfo) GetParam1() uint32 {
	if x != nil {
		return x.Param1
	}
	return 0
}

func (x *MidiMessageInfo) GetParam2() uint32 {
	if x != nil {
		return x.Param2
	}
	return 0
}

func (x *MidiMessageInfo) GetParam3() uint32 {
	if x != nil {
		return x.Param3
	}
	return 0
}

type Expression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    int32                  `protobuf:"varint,1,opt,name=expression,proto3" json:"expression,omitempty"`
	ExpressionMin float32                `protobuf:"fixed32,2,opt,name=expression_min,json=expressionMin,proto3" json:"expression_min,omitempty"`
	ExpressionMax float32                `protobuf:"fixed32,3,opt,name=expression_max,json=expressionMax,proto3" json:"expression_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_internal_qc_preset_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{12}
}

func (x *Expression) GetExpression() int32 {
	if x != nil {
		return x.Expression
	}
	return 0
}

func (x *Expression) GetExpressionMin() float32 {
	if x != nil {
		return x.ExpressionMin
	}
	return 0
}

func (x *Expression) GetExpressionMax() float32 {
	if x != nil {
		return x.ExpressionMax
	}
	return 0
}

type ExpressionBypassInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Invert         bool                   `protobuf:"varint,2,opt,name=invert,proto3" json:"invert,omitempty"`
	DelayMs        uint32                 `protobuf:"varint,3,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	LatchEmulation bool                   `protobuf:"varint,4,opt,name=latch_emulation,json=latchEmulation,proto3" json:"latch_emulation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExpressionBypassInfo) Reset() {
	*x = ExpressionBypassInfo{}
	mi := &file_internal_qc_preset_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionBypassInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionBypassInfo) ProtoMessage() {}

func (x *ExpressionBypassInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_qc_preset_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionBypassInfo.ProtoReflect.Descriptor instead.
func (*ExpressionBypassInfo) Descriptor() ([]byte, []int) {
	return file_internal_qc_preset_proto_rawDescGZIP(), []int{13}
}

func (x *ExpressionBypassInfo) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ExpressionBypassInfo) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

func (x *ExpressionBypassInfo) GetDelayMs() uint32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *ExpressionBypassInfo) GetLatchEmulation() bool {
	if x != nil {
		return x.LatchEmulation
	}
	return false
}

var File_internal_qc_preset_proto protoreflect.FileDescriptor

const file_internal_qc_preset_proto_rawDesc = "" +
	"\n" +
	"\x18internal/qc/preset.proto\x12\x02qc\"\x88\b\n" +
	"\fBinaryPreset\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\rR\x04hash\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x02R\x06volume\x12\x10\n" +
	"\x03pan\x18\x06 \x01(\x02R\x03pan\x12#\n" +
	"\rdefault_scene\x18\a \x01(\rR\fdefaultScene\x12\x1f\n" +
	"\vauthor_name\x18\b \x01(\tR\n" +
	"authorName\x12\x1b\n" +
	"\tauthor_id\x18\t \x01(\tR\bauthorId\x12\x14\n" +
	"\x05tempo\x18\n" +
	" \x01(\rR\x05tempo\x12!\n" +
	"\x06chains\x18\v \x03(\v2\t.qc.ChainR\x06chains\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12\\\n" +
	"\x1clegacy_stomp_mode_stomp_data\x18\r \x03(\v2\x1c.qc.LegacyStompModeStompDataR\x18legacyStompModeStompData\x12\x1f\n" +
	"\vscene_tempo\x18\x0e \x03(\rR\n" +
	"sceneTempo\x12!\n" +
	"\fscene_labels\x18\x0f \x03(\tR\vsceneLabels\x128\n" +
	"\rmidi_messages\x18\x10 \x03(\v2\x13.qc.MidiMessageInfoR\fmidiMessages\x12G\n" +
	"\x15midi_messages_general\x18\x11 \x03(\v2\x13.qc.MidiMessageInfoR\x13midiMessagesGeneral\x12\"\n" +
	"\x06bypass\x18\x12 \x03(\v2\n" +
	".qc.BypassR\x06bypass\x125\n" +
	"\x10tempoProgramData\x18\x13 \x03(\v2\t.qc.ModelR\x10tempoProgramData\x12\"\n" +
	"\rlayout_code_1\x18\x14 \x03(\rR\vlayoutCode1\x12\"\n" +
	"\rlayout_code_2\x18\x15 \x03(\rR\vlayoutCode2\x12'\n" +
	"\x0fcreated_version\x18\x16 \x03(\tR\x0ecreatedVersion\x12)\n" +
	"\x10modified_version\x18\x17 \x03(\tR\x0fmodifiedVersion\x12:\n" +
	"\x19oldest_compatible_version\x18\x18 \x03(\tR\x17oldestCompatibleVersion\x12\x19\n" +
	"\bcloud_id\x18\x19 \x03(\tR\acloudId\x12 \n" +
	"\vdescription\x18\x1a \x03(\tR\vdescription\x12M\n" +
	"\x16stomp_mode_assignments\x18\x1b \x03(\v2\x17.qc.StompModeAssignmentR\x14stompModeAssignments\"\xb1\x04\n" +
	"\x05Chain\x12!\n" +
	"\x06models\x18\x05 \x03(\v2\t.qc.ModelR\x06models\x12H\n" +
	"\x14split_control_points\x18\x06 \x03(\v2\x16.qc.SplitControlPointsR\x12splitControlPoints\x12%\n" +
	"\bsplitter\x18\a \x03(\v2\t.qc.ModelR\bsplitter\x12\x1f\n" +
	"\x05mixer\x18\b \x03(\v2\t.qc.ModelR\x05mixer\x120\n" +
	"\x0eoutput_control\x18\t \x03(\v2\t.qc.ModelR\routputControl\x121\n" +
	"\vsplitBypass\x18\n" +
	" \x03(\v2\x0f.qc.SceneBypassR\vsplitBypass\x12-\n" +
	"\tmixBypass\x18\v \x03(\v2\x0f.qc.SceneBypassR\tmixBypass\x126\n" +
	"\x11combined_splitter\x18\f \x03(\v2\t.qc.ModelR\x10combinedSplitter\x12.\n" +
	"\rinput_control\x18\r \x03(\v2\t.qc.ModelR\finputControl\x12\x1d\n" +
	"\tin_portid\x18\x01 \x01(\rH\x00R\binPortid\x12\x1f\n" +
	"\n" +
	"out_portid\x18\x02 \x01(\rH\x01R\toutPortid\x12\x12\n" +
	"\x03row\x18\x0e \x01(\rH\x02R\x03rowB\f\n" +
	"\n" +
	"_in_portidB\r\n" +
	"\v_out_portidB\x06\n" +
	"\x04_row\"\xfb\x01\n" +
	"\x05Model\x12!\n" +
	"\x06params\x18\x02 \x03(\v2\t.qc.ParamR\x06params\x12;\n" +
	"\x11bypass_expression\x18\x03 \x03(\v2\x0e.qc.ExpressionR\x10bypassExpression\x12N\n" +
	"\x16expression_bypass_info\x18\x04 \x03(\v2\x18.qc.ExpressionBypassInfoR\x14expressionBypassInfo\x12\x14\n" +
	"\x04hash\x18\x01 \x01(\rH\x00R\x04hash\x12\x18\n" +
	"\x06column\x18\x05 \x01(\rH\x01R\x06columnB\a\n" +
	"\x05_hashB\t\n" +
	"\a_column\"<\n" +
	"\x12SplitControlPoints\x12\x14\n" +
	"\x05split\x18\x01 \x01(\x05R\x05split\x12\x10\n" +
	"\x03mix\x18\x02 \x01(\x05R\x03mix\"Q\n" +
	"\x06Bypass\x12+\n" +
	"\tcolBypass\x18\x01 \x03(\v2\r.qc.ColBypassR\tcolBypass\x12\x12\n" +
	"\x03row\x18\x02 \x01(\rH\x00R\x03rowB\x06\n" +
	"\x04_row\"c\n" +
	"\tColBypass\x121\n" +
	"\vsceneBypass\x18\x01 \x03(\v2\x0f.qc.SceneBypassR\vsceneBypass\x12\x18\n" +
	"\x06column\x18\x02 \x01(\rH\x00R\x06columnB\t\n" +
	"\a_column\"%\n" +
	"\vSceneBypass\x12\x16\n" +
	"\x06bypass\x18\x01 \x01(\bR\x06bypass\"\xb5\x02\n" +
	"\x05Param\x121\n" +
	"\fparam_values\x18\x05 \x03(\v2\x0e.qc.ParamValueR\vparamValues\x12 \n" +
	"\n" +
	"expression\x18\x01 \x01(\x05H\x00R\n" +
	"expression\x12'\n" +
	"\x0eexpression_min\x18\x02 \x01(\x02H\x01R\rexpressionMin\x12'\n" +
	"\x0eexpression_max\x18\x03 \x01(\x02H\x02R\rexpressionMax\x12\x1f\n" +
	"\n" +
	"scene_mode\x18\x04 \x01(\bH\x03R\tsceneMode\x12\x16\n" +
	"\x05index\x18\x06 \x01(\rH\x04R\x05indexB\r\n" +
	"\v_expressionB\x11\n" +
	"\x0f_expression_minB\x11\n" +
	"\x0f_expression_maxB\r\n" +
	"\v_scene_modeB\b\n" +
	"\x06_index\"|\n" +
	"\n" +
	"ParamValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x05H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x02 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValueB\a\n" +
	"\x05value\"D\n" +
	"\x18LegacyStompModeStompData\x12\x10\n" +
	"\x03row\x18\x01 \x01(\rR\x03row\x12\x16\n" +
	"\x06column\x18\x02 \x01(\rR\x06column\"`\n" +
	"\x13StompModeAssignment\x12\x10\n" +
	"\x03row\x18\x01 \x01(\rR\x03row\x12\x16\n" +
	"\x06column\x18\x02 \x01(\rR\x06column\x12\x1f\n" +
	"\vstomp_index\x18\x03 \x01(\rR\n" +
	"stompIndex\"\x87\x01\n" +
	"\x0fMidiMessageInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\x12\x16\n" +
	"\x06param1\x18\x03 \x01(\rR\x06param1\x12\x16\n" +
	"\x06param2\x18\x04 \x01(\rR\x06param2\x12\x16\n" +
	"\x06param3\x18\x05 \x01(\rR\x06param3\"z\n" +
	"\n" +
	"Expression\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\x05R\n" +
	"expression\x12%\n" +
	"\x0eexpression_min\x18\x02 \x01(\x02R\rexpressionMin\x12%\n" +
	"\x0eexpression_max\x18\x03 \x01(\x02R\rexpressionMax\"\x86\x01\n" +
	"\x14ExpressionBypassInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x16\n" +
	"\x06invert\x18\x02 \x01(\bR\x06invert\x12\x19\n" +
	"\bdelay_ms\x18\x03 \x01(\rR\adelayMs\x12'\n" +
	"\x0flatch_emulation\x18\x04 \x01(\bR\x0elatchEmulationB1Z/github.com/d-led/guitar-modeler-mcp/internal/qcb\x06proto3"

var (
	file_internal_qc_preset_proto_rawDescOnce sync.Once
	file_internal_qc_preset_proto_rawDescData []byte
)

func file_internal_qc_preset_proto_rawDescGZIP() []byte {
	file_internal_qc_preset_proto_rawDescOnce.Do(func() {
		file_internal_qc_preset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_qc_preset_proto_rawDesc), len(file_internal_qc_preset_proto_rawDesc)))
	})
	return file_internal_qc_preset_proto_rawDescData
}

var file_internal_qc_preset_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_qc_preset_proto_goTypes = []any{
	(*BinaryPreset)(nil),             // 0: qc.BinaryPreset
	(*Chain)(nil),                    // 1: qc.Chain
	(*Model)(nil),                    // 2: qc.Model
	(*SplitControlPoints)(nil),       // 3: qc.SplitControlPoints
	(*Bypass)(nil),                   // 4: qc.Bypass
	(*ColBypass)(nil),                // 5: qc.ColBypass
	(*SceneBypass)(nil),              // 6: qc.SceneBypass
	(*Param)(nil),                    // 7: qc.Param
	(*ParamValue)(nil),               // 8: qc.ParamValue
	(*LegacyStompModeStompData)(nil), // 9: qc.LegacyStompModeStompData
	(*StompModeAssignment)(nil),      // 10: qc.StompModeAssignment
	(*MidiMessageInfo)(nil),          // 11: qc.MidiMessageInfo
	(*Expression)(nil),               // 12: qc.Expression
	(*ExpressionBypassInfo)(nil),     // 13: qc.ExpressionBypassInfo
}
var file_internal_qc_preset_proto_depIdxs = []int32{
	1,  // 0: qc.BinaryPreset.chains:type_name -> qc.Chain
	9,  // 1: qc.BinaryPreset.legacy_stomp_mode_stomp_data:type_name -> qc.LegacyStompModeStompData
	11, // 2: qc.BinaryPreset.midi_messages:type_name -> qc.MidiMessageInfo
	11, // 3: qc.BinaryPreset.midi_messages_general:type_name -> qc.MidiMessageInfo
	4,  // 4: qc.BinaryPreset.bypass:type_name -> qc.Bypass
	2,  // 5: qc.BinaryPreset.tempoProgramData:type_name -> qc.Model
	10, // 6: qc.BinaryPreset.stomp_mode_assignments:type_name -> qc.StompModeAssignment
	2,  // 7: qc.Chain.models:type_name -> qc.Model
	3,  // 8: qc.Chain.split_control_points:type_name -> qc.SplitControlPoints
	2,  // 9: qc.Chain.splitter:type_name -> qc.Model
	2,  // 10: qc.Chain.mixer:type_name -> qc.Model
	2,  // 11: qc.Chain.output_control:type_name -> qc.Model
	6,  // 12: qc.Chain.splitBypass:type_name -> qc.SceneBypass
	6,  // 13: qc.Chain.mixBypass:type_name -> qc.SceneBypass
	2,  // 14: qc.Chain.combined_splitter:type_name -> qc.Model
	2,  // 15: qc.Chain.input_control:type_name -> qc.Model
	7,  // 16: qc.Model.params:type_name -> qc.Param
	12, // 17: qc.Model.bypass_expression:type_name -> qc.Expression
	13, // 18: qc.Model.expression_bypass_info:type_name -> qc.ExpressionBypassInfo
	5,  // 19: qc.Bypass.colBypass:type_name -> qc.ColBypass
	6,  // 20: qc.ColBypass.sceneBypass:type_name -> qc.SceneBypass
	8,  // 21: qc.Param.param_values:type_name -> qc.ParamValue
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_internal_qc_preset_proto_init() }
func file_internal_qc_preset_proto_init() {
	if File_internal_qc_preset_proto != nil {
		return
	}
	file_internal_qc_preset_proto_msgTypes[1].OneofWrappers = []any{
		(*Chain_InPortid)(nil),
		(*Chain_OutPortid)(nil),
		(*Chain_Row)(nil),
	}
	file_internal_qc_preset_proto_msgTypes[2].OneofWrappers = []any{
		(*Model_Hash)(nil),
		(*Model_Column)(nil),
	}
	file_internal_qc_preset_proto_msgTypes[4].OneofWrappers = []any{
		(*Bypass_Row)(nil),
	}
	file_internal_qc_preset_proto_msgTypes[5].OneofWrappers = []any{
		(*ColBypass_Column)(nil),
	}
	file_internal_qc_preset_proto_msgTypes[7].OneofWrappers = []any{
		(*Param_Expression)(nil),
		(*Param_ExpressionMin)(nil),
		(*Param_ExpressionMax)(nil),
		(*Param_SceneMode)(nil),
		(*Param_Index)(nil),
	}
	file_internal_qc_preset_proto_msgTypes[8].OneofWrappers = []any{
		(*ParamValue_IntValue)(nil),
		(*ParamValue_FloatValue)(nil),
		(*ParamValue_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_qc_preset_proto_rawDesc), len(file_internal_qc_preset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_qc_preset_proto_goTypes,
		DependencyIndexes: file_internal_qc_preset_proto_depIdxs,
		MessageInfos:      file_internal_qc_preset_proto_msgTypes,
	}.Build()
	File_internal_qc_preset_proto = out.File
	file_internal_qc_preset_proto_goTypes = nil
	file_internal_qc_preset_proto_depIdxs = nil
}
