package catalog

// fx is the list of effect modules that can be placed in a rig chain. Names are
// the exact module names used by the device, so they can be written verbatim
// into the Chain.ModuleTypeN slots of a rig file.
var fx = []FX{
	// Drive / distortion / fuzz
	{Name: "White Boost", Category: "drive", Description: "Clean, transparent boost (Xotic RC Booster style)."},
	{Name: "Green JRC-OD", Category: "drive", Description: "Green overdrive (Ibanez TS808 Tube Screamer style)."},
	{Name: "D250 Drive", Category: "drive", Description: "Amp-in-a-box drive (DOD 250 style)."},
	{Name: "Glorious Drive", Category: "drive", Description: "Transparent low-to-medium gain drive."},
	{Name: "S1 Drive", Category: "drive", Description: "Medium gain, amp-like overdrive."},
	{Name: "B2 Drive", Category: "drive", Description: "Bright, cutting overdrive."},
	{Name: "K Drive", Category: "drive", Description: "High gain distortion with a tight low end."},
	{Name: "DC Distort", Category: "drive", Description: "Classic distortion (BOSS DS-1 style)."},
	{Name: "D1 Dist", Category: "drive", Description: "Hard-clipping distortion."},
	{Name: "MX Dist", Category: "drive", Description: "Aggressive modern distortion."},
	{Name: "Anxiety OD", Category: "drive", Description: "Overdrive voiced for modern metal rhythm."},
	{Name: "Anxiety OD V2", Category: "drive", Description: "Refined version of Anxiety OD."},
	{Name: "B Dist 7000", Category: "drive", Description: "Bass distortion."},
	{Name: "Black OP", Category: "drive", Description: "Dark, gated fuzz-style distortion."},
	{Name: "Tri Fuzz", Category: "drive", Description: "Three-transistor fuzz."},
	{Name: "Round Fuzz", Category: "drive", Description: "Smooth, round fuzz (EHX Big Muff style)."},
	{Name: "Oct Fuzz", Category: "drive", Description: "Octave-up fuzz."},
	{Name: "8-Bit Crush", Category: "drive", Description: "Lo-fi bitcrusher with drive."},

	// Dynamics / EQ
	{Name: "DynIII Comp", Category: "dynamics/eq", Description: "Studio-style compressor."},
	{Name: "Gray Comp", Category: "dynamics/eq", Description: "Ross-style optical compressor."},
	{Name: "Side Comp", Category: "dynamics/eq", Description: "Compressor with sidechain options."},
	{Name: "Gate", Category: "dynamics/eq", Description: "Noise gate."},
	{Name: "Noise Filter", Category: "dynamics/eq", Description: "Adaptive noise reduction."},
	{Name: "Hold", Category: "dynamics/eq", Description: "Freeze/hold effect."},
	{Name: "Auto Swell", Category: "dynamics/eq", Description: "Volume swell triggered by picking."},
	{Name: "Acoustic Pre", Category: "dynamics/eq", Description: "Acoustic guitar preamp/EQ."},
	{Name: "Graphic EQ", Category: "dynamics/eq", Description: "Graphic equalizer."},
	{Name: "Para EQ", Category: "dynamics/eq", Description: "Parametric equalizer."},
	{Name: "Ten Freq EQ", Category: "dynamics/eq", Description: "Ten-band graphic equalizer."},
	{Name: "Bass EQ", Category: "dynamics/eq", Description: "Bass-specific equalizer."},

	// Filter / wah / expression
	{Name: "Black Wah", Category: "filter/wah", Description: "Classic wah."},
	{Name: "More Wah", Category: "filter/wah", Description: "Wah with extended sweep."},
	{Name: "Shine Wah", Category: "filter/wah", Description: "Bright, vocal wah."},
	{Name: "White Bass Wah", Category: "filter/wah", Description: "Bass-voiced wah."},
	{Name: "Env Filter", Category: "filter/wah", Description: "Envelope follower auto-wah."},
	{Name: "Tron Filter", Category: "filter/wah", Description: "Mu-tron style envelope filter."},
	{Name: "AIR Filter", Category: "filter/wah", Description: "Sweeping filter with movement."},
	{Name: "Volume", Category: "filter/wah", Description: "Volume pedal module."},
	{Name: "Panner", Category: "filter/wah", Description: "Stereo auto-panner."},
	{Name: "Feedback", Category: "filter/wah", Description: "Controlled feedback generator."},
	{Name: "Time Warp", Category: "filter/wah", Description: "Expression-controlled time modulation."},
	{Name: "Wham", Category: "filter/wah", Description: "Expression-controlled pitch (DigiTech Whammy style)."},
	{Name: "Chord Wham", Category: "pitch", Description: "Expression-controlled chord pitch shifting."},

	// Modulation
	{Name: "Chorus", Category: "modulation", Description: "Classic analog chorus."},
	{Name: "Multi Chorus", Category: "modulation", Description: "Rich multi-voice chorus."},
	{Name: "Dim Chorus", Category: "modulation", Description: "Subtle, dimension-style chorus."},
	{Name: "Flanger", Category: "modulation", Description: "Classic flanger."},
	{Name: "AIR Flanger", Category: "modulation", Description: "Wide, airy flanger."},
	{Name: "Vibrato", Category: "modulation", Description: "Pitch vibrato."},
	{Name: "AIR Vibrato", Category: "modulation", Description: "Airy, soft vibrato."},
	{Name: "Tremolo", Category: "modulation", Description: "Amplitude tremolo."},
	{Name: "Rotary", Category: "modulation", Description: "Rotary speaker simulation."},
	{Name: "Stone Phaser", Category: "modulation", Description: "Phase shifter (EHX Small Stone style)."},
	{Name: "Orange Phaser", Category: "modulation", Description: "Warm phase shifter (MXR Phase 90 style)."},
	{Name: "Vibe Phaser", Category: "modulation", Description: "Uni-vibe style phaser."},
	{Name: "Tron Phaser", Category: "modulation", Description: "Envelope-triggered phaser."},
	{Name: "Ring Mod", Category: "modulation", Description: "Ring modulator."},
	{Name: "Stereo Doubler", Category: "modulation", Description: "Stereo width doubler."},
	{Name: "Detune", Category: "pitch", Description: "Subtle detune chorus for width."},
	{Name: "Smart Harm", Category: "pitch", Description: "Intelligent harmonizer."},
	{Name: "Harm", Category: "pitch", Description: "Diatonic harmonizer."},
	{Name: "Octaves", Category: "pitch", Description: "Octave up/down pitch shifter."},
	{Name: "Octaves Up", Category: "pitch", Description: "Octave-up pitch shifter."},
	{Name: "Drop Tune", Category: "pitch", Description: "Drop-tuning pitch shifter."},

	// Delay / reverb
	{Name: "AIR Delay", Category: "delay/reverb", Description: "Wide, atmospheric digital delay."},
	{Name: "Dyn Delay", Category: "delay/reverb", Description: "Dynamic ducking delay."},
	{Name: "BBD Delay", Category: "delay/reverb", Description: "Analog bucket-brigade delay."},
	{Name: "Tape Echo", Category: "delay/reverb", Description: "Tape echo with wow, flutter and hiss."},
	{Name: "Pitch Delay", Category: "delay/reverb", Description: "Delay with pitch-shifted repeats."},
	{Name: "Reso Delay", Category: "delay/reverb", Description: "Resonant filtered delay."},
	{Name: "Reverse Delay", Category: "delay/reverb", Description: "Backwards delay."},
	{Name: "AIR Reverb", Category: "delay/reverb", Description: "Expansive hall-style reverb."},
	{Name: "Ambi Verb", Category: "delay/reverb", Description: "Ambient reverb with long tails."},
	{Name: "Eleven Reverb", Category: "delay/reverb", Description: "Natural room and hall reverb."},
	{Name: "Party Verb", Category: "delay/reverb", Description: "Lush, modulated reverb."},
	{Name: "Spring Reverb", Category: "delay/reverb", Description: "Spring tank reverb."},
	{Name: "Shimmer", Category: "delay/reverb", Description: "Pitch-shifted shimmer reverb."},

	// Utility
	{Name: "Acoust Sim", Category: "utility", Description: "Electric-to-acoustic simulator."},
	{Name: "FX-Loop", Category: "utility", Description: "Insert point for external pedals."},
	{Name: "IR", Category: "utility", Description: "Impulse response loader."},
	{Name: "IR (1024)", Category: "utility", Description: "High-resolution impulse response loader."},
}
