package mooer

import "github.com/d-led/guitar-modeler-mcp/internal/device"

// ge200 is the Mooer GE200. Its model tables come from the official GE200
// owner's manual (the "based on" column) and are shared by the GE150 — the two
// devices ship the same 55 amps, 26 cabs and 151 effects. The GE200 edits
// presets over USB, so it supports file exchange.

func ge200() Model {
	return Model{
		Name:         "ge200",
		Display:      "Mooer GE200",
		FileExchange: true,
		FileExt:      ".mo",
		ModuleOrder:  append([]string(nil), ModuleOrder...),
		Amps:         mooerAmps,
		Cabs:         mooerCabs,
		Effects:      mooerEffects,
	}
}

// mooerAmps is the shared 55-amp list (GE200/GE150), in effect_type order.
var mooerAmps = device.Items(
	[2]string{"65 US DLX", "Fender '65 Deluxe Reverb"},
	[2]string{"65 US TW", "Fender '65 Twin Reverb"},
	[2]string{"59 US BASS", "Fender '59 Bassman"},
	[2]string{"US SONIC", "Fender Super-Sonic"},
	[2]string{"US BLUES CL", "Fender Blues Deluxe"},
	[2]string{"US BLUES OD", "Fender Blues Deluxe"},
	[2]string{"800", "Marshall JCM800"},
	[2]string{"900", "Marshall JCM900"},
	[2]string{"PLX 100", "Marshall Super Lead Plexi 100"},
	[2]string{"650 CL", "Engl E650"},
	[2]string{"650 DS", "Engl E650"},
	[2]string{"POWERBELL CL", "Engl Powerball"},
	[2]string{"POWERBELL DS", "Engl Powerball"},
	[2]string{"BLACKNIGHT CL", "Engl E650 Blackmore"},
	[2]string{"BLACKNIGHT DS", "Engl E650 Blackmore"},
	[2]string{"MARK III CL", "Mesa Boogie Mark III"},
	[2]string{"MARK III DS", "Mesa Boogie Mark III"},
	[2]string{"MARK V CL", "Mesa Boogie Mark V"},
	[2]string{"MARK V DS", "Mesa Boogie Mark V"},
	[2]string{"TRI REC CL", "Mesa Boogie Triple Rectifier"},
	[2]string{"TRI REC DS", "Mesa Boogie Triple Rectifier"},
	[2]string{"ROCK VRB CL", "Orange Rockerverb"},
	[2]string{"ROCK VRB DS", "Orange Rockerverb"},
	[2]string{"CITRUS 30", "Orange AD30"},
	[2]string{"CITRUS 50", "Orange OR50"},
	[2]string{"SLOW 100 CR", "Soldano SLO-100"},
	[2]string{"SLOW 100 DS", "Soldano SLO-100"},
	[2]string{"DR.ZEE 18", "Dr. Z Maz 18"},
	[2]string{"DR.ZEE RECK", "Dr. Z Z-Wreck"},
	[2]string{"JET 100H CL", "Jet City JCA100H"},
	[2]string{"JET 100H OD", "Jet City JCA100H"},
	[2]string{"JAZZ 120", "Roland JC-120"},
	[2]string{"UK30 CL", "Vox AC30"},
	[2]string{"UK30 OD", "Vox AC30"},
	[2]string{"HWT 4103", "Hiwatt DR-103"},
	[2]string{"PV 5050 CL", "Peavey 5150"},
	[2]string{"PV 5050 DS", "Peavey 5150"},
	[2]string{"REGAL TONE CL", "Tone King Falcon"},
	[2]string{"REGAL TONE OD1", "Tone King Falcon"},
	[2]string{"REGAL TONE OD2", "Tone King Falcon"},
	[2]string{"CAROL CL", "Two Rock Coral"},
	[2]string{"CAROL OD", "Two Rock Coral"},
	[2]string{"CARDEFF", "Two Rock Cardiff"},
	[2]string{"EV 5050 CL", "EVH 5150"},
	[2]string{"EV 5050 DS", "EVH 5150"},
	[2]string{"HT CLUB CL", "Blackstar HT Stage 100"},
	[2]string{"HT CLUB DS", "Blackstar HT Stage 100"},
	[2]string{"HUGEN CL", "Diezel Hagen"},
	[2]string{"HUGEN OD", "Diezel Hagen"},
	[2]string{"HUGEN DS", "Diezel Hagen"},
	[2]string{"KOCHE OD", "Koch Powertone"},
	[2]string{"KOCHE DS", "Koch Powertone"},
	[2]string{"ACOUSTIC 1", "Acoustic Simulator"},
	[2]string{"ACOUSTIC 2", "Acoustic Simulator"},
	[2]string{"ACOUSTIC 3", "Acoustic Simulator"},
)

// mooerCabs is the shared 26-cab list, in effect_type order.
var mooerCabs = device.Items(
	[2]string{"US DLX 112", "Fender Deluxe Reverb 1x12"},
	[2]string{"US TWN 212", "Fender Twin Reverb 2x12"},
	[2]string{"US BASS 410", "Fender Bassman 4x10"},
	[2]string{"SONIC 112", "Fender Super-Sonic 1x12"},
	[2]string{"BLUES 112", "Fender Blues Deluxe 1x12"},
	[2]string{"1960 412", "Marshall 1960A 4x12"},
	[2]string{"EAGLE P 412", "Engl Pro 4x12"},
	[2]string{"EAGLE S 412", "Engl Vintage 4x12"},
	[2]string{"MARK 112", "Mesa Boogie Mark 1x12"},
	[2]string{"REC 412", "Mesa Boogie Rectifier 4x12"},
	[2]string{"CITRUS 412", "Orange PPC412"},
	[2]string{"CITRUS 212", "Orange PPC212"},
	[2]string{"SLOW 412", "Soldano SLO 4x12"},
	[2]string{"DR.ZEE 112", "Dr. Z Maz 1x12"},
	[2]string{"DR.ZEE 212", "Dr. Z Z-Wreck 2x12"},
	[2]string{"JAZZ 212", "Roland JC-120 2x12"},
	[2]string{"UK 212", "Vox AC30 2x12"},
	[2]string{"HWT 412", "Hiwatt 4x12"},
	[2]string{"PV 5050 412", "Peavey 5150 4x12"},
	[2]string{"REGAL TONE 110", "Tone King Falcon 1x10"},
	[2]string{"TWO STONES 212", "Two Rock 2x12"},
	[2]string{"CARDEFF 112", "Two Rock 1x12"},
	[2]string{"EV 5050 412", "EVH 5150 4x12"},
	[2]string{"HT 412", "Blackstar HT 4x12"},
	[2]string{"GAS STATION 412", "Diezel Hagen 4x12"},
	[2]string{"ACOUSTIC 112", "Acoustic 1x12"},
)

// mooerEffects is the shared per-module effect list, in effect_type order.
var mooerEffects = map[string][]Item{
	"fx": device.Items(
		[2]string{"CRY WAH", "Dunlop GCB95"},
		[2]string{"535 WAH", "Dunlop 535Q"},
		[2]string{"AUTO WAH", "Mooer @Wah"},
		[2]string{"TALK WAH AH", "Mooer RedKid Talk Wah"},
		[2]string{"TALK WAH OH", "Mooer RedKid Talk Wah"},
		[2]string{"TOUCH WAH", "Envelope Filter"},
		[2]string{"YELLOW COMP", "Mooer Yellow Comp"},
		[2]string{"BLUE COMP", "Mooer Blue Comp"},
	),
	"od": device.Items(
		[2]string{"TUBE DR", "B.K. Butler Tube Driver"},
		[2]string{"808", "Ibanez TS808"},
		[2]string{"PURE BOOST", "Mooer Pure Boost"},
		[2]string{"FLEX BOOST", "Mooer Flex Boost"},
		[2]string{"DDRIVE", "Barber Direct Drive"},
		[2]string{"BLACKRAT", "ProCo Rat"},
		[2]string{"GREY FAZE", "Dunlop Fuzz Face"},
		[2]string{"MUFFY", "EHX Big Muff"},
		[2]string{"MTLZONE", "BOSS Metal Zone"},
		[2]string{"MTLMASTER", "Digitech Metal Master"},
		[2]string{"OBSESSIVE DIST", "Fulltone OCD"},
		[2]string{"JIMMY OD", "Paul Cochrane Timmy"},
		[2]string{"FULLDRV", "Fulltone Fulldrive 2"},
		[2]string{"SHRED", "Marshall Shredmaster"},
		[2]string{"BeeBee PRE", "Xotic BB Preamp"},
		[2]string{"BeeBee+", "Xotic BB Plus"},
		[2]string{"RIET", "Suhr Riot"},
		[2]string{"TIGHT DS", "Amptweaker TightRock"},
		[2]string{"FULLDS", "Fulltone GT-500"},
		[2]string{"GOLD CLON", "Klon Centaur"},
	),
	"ns": device.Items(
		[2]string{"NOISE KILLER", "Mooer Noise Killer"},
		[2]string{"INTEL REDUCER", "Mooer Intelligent Noise Reduction"},
		[2]string{"NOISE GATE", "Mooer Digital Noise Gate"},
	),
	"eq": device.Items(
		[2]string{"EQ-G", "5-band Graphic EQ"},
		[2]string{"EQ-B", "5-band Bass Graphic EQ"},
		[2]string{"EQ-G6", "6-band Graphic EQ"},
		[2]string{"CUSTOM EQ", "Parametric EQ"},
	),
	"mod": device.Items(
		[2]string{"PHASER", "MXR Phase 90"},
		[2]string{"STEP PHASER", "Square Wave Phaser"},
		[2]string{"FAT PHASER", "Low Frequency Phaser"},
		[2]string{"FLANGER", "EHX Electric Mistress"},
		[2]string{"JET FLANGER", "Mooer Jet Flanger"},
		[2]string{"TREMOLO", "Demeter Tremulator"},
		[2]string{"STUTTER", "Choppy Filter"},
		[2]string{"VIBRATO", "Pitch Modulation"},
		[2]string{"PITCH SHIFT", "Whammy Pitch Shifter"},
		[2]string{"DETUNE", "Detune"},
		[2]string{"ROTARY", "Leslie Rotating Speaker"},
		[2]string{"ANA-CHORUS", "BOSS CE-2 Chorus"},
		[2]string{"TRI-CHORUS", "Multi-voice Chorus"},
		[2]string{"RING MOD", "Ring Modulator"},
		[2]string{"Q-FILTER", "Notch Filter"},
		[2]string{"HIGH PASS", "High Pass Filter"},
		[2]string{"LOW PASS", "Low Pass Filter"},
		[2]string{"SLOW GEAR", "BOSS SG-1 Slow Gear"},
		[2]string{"LOFI", "Low Rate Sampling Filter"},
	),
	"delay": device.Items(
		[2]string{"DIGITAL", "Digital Delay"},
		[2]string{"ANALOG", "Analog BBD Delay"},
		[2]string{"DYNAMIC", "Dynamic Delay"},
		[2]string{"REAL", "Natural Echo"},
		[2]string{"TAPE", "Tape Echo"},
		[2]string{"MOD", "Modulated Delay"},
		[2]string{"REVERSE", "Reverse Delay"},
		[2]string{"DUAL DELAY", "Dual Delay"},
		[2]string{"PINGPONG", "Stereo Ping-Pong Delay"},
	),
	"reverb": device.Items(
		[2]string{"ROOM", "Room Reverb"},
		[2]string{"HALL", "Hall Reverb"},
		[2]string{"CHURCH", "Church Reverb"},
		[2]string{"PLATE", "Plate Reverb"},
		[2]string{"SPRING", "Spring Reverb"},
		[2]string{"MOD", "Modulated Reverb"},
		[2]string{"CAVE", "Cave Reverb"},
	),
}
