#!/usr/bin/env bash
# Regenerate cli.md from the Cobra command help output.
#
# Usage: bash scripts/gen-cli-help.sh
set -euo pipefail

cd "$(dirname "$0")/.."

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
bin="$tmp/guitar-modeler-mcp"

go build -o "$bin" .

# Command paths, in the same order they appear in the root help. An empty
# string means the root command itself.
commands=(
  ""
  "serve"
  "catalog"
  "catalog amps"
  "catalog cabs"
  "catalog fx"
  "catalog fx-categories"
  "catalog mics"
  "catalog params"
  "catalog presets"
  "catalog variants"
  "translate"
  "translate amp"
  "translate cab"
  "translate mic"
  "search"
  "fx-placement"
  "design"
  "report"
  "decode"
  "diff"
  "level"
  "setlist"
  "mcp"
  "mcp install"
  "mcp uninstall"
  "device"
  "device list"
  "map"
)

out="cli.md"

{
  echo "# CLI reference"
  echo
  echo "Generated by \`scripts/gen-cli-help.sh\`. Do not edit by hand."
  echo
  for c in "${commands[@]}"; do
    if [[ -z "$c" ]]; then
      heading="guitar-modeler-mcp"
    else
      heading="guitar-modeler-mcp $c"
    fi
    echo "## \`$heading\`"
    echo
    echo '```text'
    # Intentional word splitting: $c holds the subcommand path.
    # shellcheck disable=SC2086
    "$bin" $c --help
    echo '```'
    echo
  done
} > "$out"

echo "wrote $out"
