// Package gp200 is the device-specific backend for the Valeton GP-200
// multi-effects processor. It models the device's fixed eleven-block signal
// path and the binary .prst preset file format, and is intentionally
// independent of every other device backend (see internal/catalog and
// internal/rig for the HeadRush Gigboard, internal/mooer for Mooer).
//
// The GP-200's eleven blocks are fixed-function: PRE, WAH, DST, AMP, NR, CAB,
// EQ, MOD, DLY, RVB and VOL. Unlike the Gigboard or Mooer devices, a block's
// job is determined by its position, not by the effect loaded into it, and
// each effect is identified on the wire by a 32-bit code rather than a
// per-module index. The effect tables in catalog_data.go (generated by
// scripts/extract-gp200-catalog.cjs) are the ground truth for those codes.
package gp200

import (
	"fmt"
	"strings"
)

// Effect is one effect model on the device: its 32-bit on-wire code, display
// name and the module catalog it is listed under in the editor.
type Effect struct {
	Code   uint32 `json:"code"`
	Name   string `json:"name"`
	Module string `json:"module"`
}

// ParamDef is one editable parameter of an effect. Index is the position in the
// block's 15-float32 parameter array; Kind is "knob", "switch" or "combox".
// Knobs carry a Min/Max/Step range; switches and comboxes carry the option
// display names in id order.
type ParamDef struct {
	Index   int      `json:"index"`
	Name    string   `json:"name"`
	Kind    string   `json:"kind"`
	Min     float64  `json:"min,omitempty"`
	Max     float64  `json:"max,omitempty"`
	Step    float64  `json:"step,omitempty"`
	Default float64  `json:"default"`
	Options []string `json:"options,omitempty"`
}

// SlotModules returns the fixed eleven-block signal path, in physical slot
// order (slot 0 = PRE ... slot 10 = VOL).
func SlotModules() []string {
	return append([]string(nil), slotModules...)
}

// supplementalInspiredBy fills the few effect names whose original hardware is
// only documented in the community tone reference (valeton-gp200-referencias).
// It is keyed by display name and merged after the generated table, so the
// generated file never has to be hand-edited.
var supplementalInspiredBy = map[string]string{
	"Gate 3":       "Inverse expander (dynamic signal processor)",
	"Hammy":        "DigiTech® Whammy® (monophonic pitch shifter)",
	"Harmonizer 1": "Monophonic single-voice harmonizer",
	"Harmonizer 2": "Monophonic dual-voice harmonizer",
	"Revolt":       "Suhr® Riot Distortion",
	"Flex OD":      "Simple distortion for guitar and bass",
	"Bass OD":      "Bass overdrive",
	"Empire OD":    "Analog.Man™ Prince of Tone",
	"Bass Hammer":  "Aguilar® Tone Hammer",
	"Flagman Dist": "Modern British high-gain dirt box",
	"A-Chorus":     "Classic 1980s chorus pedal",
	"Vibrato T":    "Vibrato with dynamic depth control",
	"Hold":         "Freeze effect",
	"Freeze":       "Freeze effect",
	"Dual Echo":    "Delay combining feedback with pitch-shifted slices",
	"Ice Delay":    "Delay combining feedback with pitch-shifted slices",
	"Broken Delay": "Creative \"fragmented\" delay",
	"Amp Spring":   "Solid-state combo-amp spring reverb",
	"Tube Spring":  "Vintage tube-driven spring reverb",
}

// Effects returns every effect model, in catalog (code) order.
func Effects() []Effect {
	out := make([]Effect, len(effects))
	for i, e := range effects {
		out[i] = Effect(e)
	}
	return out
}

// EffectByCode returns the effect for an on-wire code.
func EffectByCode(code uint32) (Effect, bool) {
	for _, e := range effects {
		if e.Code == code {
			return Effect(e), true
		}
	}
	return Effect{}, false
}

// EffectCode returns the canonical (lowest) code for a named effect, matching
// case-insensitively. Some names (e.g. "User IR", "SnapTone") span several
// codes; the lowest code is the default and CodesForName returns them all.
func EffectCode(name string) (uint32, bool) {
	for _, e := range effects {
		if strings.EqualFold(e.Name, name) {
			return e.Code, true
		}
	}
	return 0, false
}

// CodesForName returns every code that a named effect maps to, in code order.
func CodesForName(name string) []uint32 {
	var out []uint32
	for _, e := range effects {
		if strings.EqualFold(e.Name, name) {
			out = append(out, e.Code)
		}
	}
	return out
}

// InspiredBy returns the real hardware an effect emulates, or "" when the
// original is not documented (e.g. the SnapTone NAM capture slots).
func InspiredBy(name string) string {
	for _, e := range effects {
		if strings.EqualFold(e.Name, name) {
			if d, ok := inspiredBy[e.Name]; ok {
				return d
			}
			return supplementalInspiredBy[e.Name]
		}
	}
	return ""
}

// ModuleEffects returns the effects listed under one module catalog
// (PRE, WAH, DST, AMP, NR, CAB, EQ, MOD, DLY, RVB or VOL), in code order.
func ModuleEffects(module string) []Effect {
	var out []Effect
	for _, e := range effects {
		if strings.EqualFold(e.Module, module) {
			out = append(out, Effect(e))
		}
	}
	return out
}

// Amps returns the amplifier models (module AMP), in code order.
func Amps() []Effect { return ModuleEffects("AMP") }

// Cabs returns the cabinet models (module CAB), in code order.
func Cabs() []Effect { return ModuleEffects("CAB") }

// EffectsByModule returns every module that has effects, each mapped to its
// effects in code order. Modules with no models are omitted.
func EffectsByModule() map[string][]Effect {
	out := map[string][]Effect{}
	for _, mod := range slotModules {
		if mod == "AMP" || mod == "CAB" {
			continue
		}
		out[mod] = ModuleEffects(mod)
	}
	return out
}

// DefaultParams returns the editor defaults for an effect's 15 parameter
// values, so a newly placed block starts from a sensible sound.
func DefaultParams(code uint32) [15]float32 {
	var out [15]float32
	for _, p := range effectParams[code] {
		if p.Index >= 0 && p.Index < len(out) {
			out[p.Index] = float32(p.Default)
		}
	}
	return out
}

// Params returns the editable parameter definitions for an effect, in index
// order.
func Params(code uint32) []ParamDef {
	return effectParams[code]
}

// ParamNames returns the display names of an effect's parameters, indexed by
// parameter position (the index into the 15-float32 array). Unused positions
// are the empty string.
func ParamNames(code uint32) []string {
	names := make([]string, 15)
	for _, p := range effectParams[code] {
		if p.Index >= 0 && p.Index < len(names) {
			names[p.Index] = p.Name
		}
	}
	return names
}

// SetParam writes a value into a block's parameter array, addressed by
// parameter name (matched case-insensitively against the editor's labels,
// e.g. "low cut" matches "Low Cut").
func SetParam(b *Block, key string, value float32) error {
	idx, err := paramIndex(b.EffectID, key)
	if err != nil {
		return err
	}
	if idx < 0 || idx >= len(b.Params) {
		return fmt.Errorf("parameter %q index %d out of range", key, idx)
	}
	b.Params[idx] = value
	return nil
}

// ApplyNamedParams writes a set of name-keyed overrides onto a block, returning
// the names that did not match any of the effect's parameters (so callers can
// surface them instead of silently dropping them).
func ApplyNamedParams(b *Block, overrides map[string]float32) []string {
	var rejected []string
	for name, value := range overrides {
		if err := SetParam(b, name, value); err != nil {
			rejected = append(rejected, name)
		}
	}
	return rejected
}

func paramIndex(code uint32, key string) (int, error) {
	for _, p := range effectParams[code] {
		if strings.EqualFold(p.Name, key) {
			return p.Index, nil
		}
	}
	return -1, fmt.Errorf("effect %q has no parameter %q", EffectName(code), key)
}
